### PR TITLE
Update Yavli filters

### PR DESCRIPTION
**Pull request by ryanbr**
This will fix Yavli on related sites and `newser.com` (also a Yavli site). Preventing forced popups and adblock checks.

### CODE REVIEW

**Comment by ryanbr** [comment]
Hmm, need to re-think this one.

**Comment by TheStinkySkunk** [comment]
@ryanbr : You have nothing else to do during this Christmas period?

We don't html pop since  2018 ... and you have already rotten us several WE with your Sunday updates.

In 2019, we have determined strict quality rules for inserting ads (systematically outside of content).

Leave us alone until January, we restart the game from 02 ?

Personally I have a life ... and there I have to take care of the gifts for the kids.

Take a break and enjoy your family, you deserve it!

Merry Christmas to you and all your family and all our wishes for 2020 !

Best Regards
Yavli Team

**Comment by mapx-** [comment]
`wjt.at_g`  does not work, already changed

**Comment by ryanbr** [comment]
Do you have a better suggestion @mapx-

**Comment by ryanbr** [comment]
Just tested comments on newser. https://www.newser.com/story/comments/284667/1-woman-killed-1-injured-in-vicious-dog-attack.html (via a vpn) Its safe.

**Comment by mapx-** [comment]
when I add `newser.com##+js(aopr, document.head.appendChild)` for uBo the comments are gone.
Testing in ABP is difficult => I get anti adb screen and I don't have all the redirects / features as in uBo .. to fix the issue

**Comment by wizmak** [comment]
`#$#abort-on-property-read document.head.appendChild` doesn't seem to work anymore, as tried on rightwingtribune.com, grammarist.com and newser.com

**Comment by okiehsch** [comment]
Well, I mean if you are fine with aborting setTimeout then I would suggest you use the original pull request of aborting Math.floor that will break far less.
Aborting setTimeout for such a huge amount of sites is -  no offence - crazy it will break videos,  most dropdown menus, search, comments, the ability to login, etc.

Example: 
````
https://www.newser.com/story/284673/teen-brain-damaged-after-breast-surgery-parents.html
````
The video is gone, try search or click "More" or click to see all comments, etc.

If you don't mind some site breakage use `Math.floor` that will only break the "see all comments" part and will also break far less on all the other sites.

**Comment by TheStinkySkunk** [comment]
+1 with @okiehsch

That's crazy filter which can only cause problems to your users with a lot of website (and Jquery...).

Tell me what problem you've got with newser ads, i'll see what I can do.

**Comment by TheStinkySkunk** [comment]
US Woman Mayuri Singh Is 19th Victim of New Zealand Eruption

**Comment by wizmak** [comment]
I'm not a fan of aborting `setTimeout`, but seems like something is fishy here, I tested the filter on newser.com (and few others), and it was not breaking video, search or comments.
In all cases, looks like changes are already made on `newser.com` and ads are back, let me know if there are any other affected websites.

**Comment by TheStinkySkunk** [comment]
@wizmak : I just changed my code ...

Since we transfer our licenses directly to our publishers (by contract) and you block content served by their domain name, you are directly touching the intellectual property of publishers with your filters ...

When I no longer have access to javascript, I will directly inject HTML blocks, "I'm man in the middle"

**Comment by okiehsch** [comment]
Yes, they changed their code and you can now remove `setTimeout` because the ads are back anyway.
Your filter will break functionality on sites that no longer use yavli.
For example go to 
`https://www.youthhealthmag.com/`
Aborting `setTimeout` breaks thumbnails, search, the subscribe button, etc.

**Comment by okiehsch** [comment]
>  you are directly touching the intellectual property of publishers with your filters

Don't be so dramatic, I am not directly touching the intellectual property if I decide to not run some script on **my** device.

**Comment by TheStinkySkunk** [comment]
It's your point of view.

Whenever you broadcast a
filtering rule which directly affects the functionality of the site, it is the sites which receive complaint messages from YOUR users and this is not without consequence.

In 2019, smed79 released 3 filtering rules that had the effect of preventing the end customer from accessing the content, is that normal?

The current filtering of setTimeout illustrates very well the way you work: we broadcast and we will see then.

**Comment by wizmak** [comment]
Removed filter as it's not longer working 464b704

**Comment by okiehsch** [comment]
> Whenever you broadcast a filtering rule which directly affects the functionality of the site, it is the sites which receive complaint messages from YOUR users and this is not without consequence.

I agree with you that filters should not break site functionality, I only disagreed with your claim that such a filter would somehow "directly touch the intellectual property of publishers".
That would be the case if I hack the site and remove the ads that way. 😉

**Comment by wizmak** [comment]
@TheStinkySkunk 
> We are ready to discuss with you, tell me what is your problem with our ads.

It's simple, your job is to deliver ads, and my job is to enable users to block them, so I have no problems with your ads 😉

**Comment by TheStinkySkunk** [comment]
The javascript scripts of a website are also part of intellectual property.

I love your work ... but seriously do tests before distribution, at least to guarantee your users a good experience with your product.

**Comment by TheStinkySkunk** [comment]
@wizmak : I've got a job for you ;)

I think your job is to tax media to have the right to broadcast ads to your users... Welcome in North Korea.

**Comment by mapx-** [comment]
@wizmak test these filters
```
newser.com#$#abort-on-property-read document.styleSheets
newser.com##.gridAd
```

**Comment by mapx-** [comment]
an alternative could be 
`||newser.com^$csp=style-src *`

but with some minor(?) breakage

**Comment by wizmak** [comment]
> ```
> newser.com#$#abort-on-property-read document.styleSheets
> newser.com##.gridAd
> ```

@mapx- doesn't work

**Comment by wizmak** [comment]
> an alternative could be
> `||newser.com^$csp=style-src *`
> 
> but with some minor(?) breakage

Went with 665aba1 to avoid any breakage.

**Pull request merged**
