### PR TITLE
Facebook rule - more specific version

### PR DESCRIPTION
**Pull request by peace2000**
Hi, even though the current rule works fine, I feel that it's a bit generic... Made a suggestion to make it more specific and safe.

### CODE REVIEW

**Comment by arsykan** [comment]
@peace2000 thanks for your contribution!

it doesn't match unless I removed this part `[aria-label]` could you recheck?
what browser do you use? mine is chrome

**Comment by peace2000** [comment]
Strange. I use Firefox.

The issue with Facebook is that they sometimes show those sponsored ads but sometimes not. I took a screenshot of that elemen't DOM structure (luckily, before it disappeared again..)

https://user-images.githubusercontent.com/17256841/132045514-1126333e-a7d6-4ec5-b9f2-aae19b674c1e.png

How does it look for you then?

**Comment by peace2000** [comment]
I switched to Chrome now and I can see that ad again, and for me it gives that [aria-label] still.

**Comment by arsykan** [comment]
interesting...
I use generally English but we test before pushing filters on German, Spanish, French languages as well.

please let this issue open until next week, we will double-check. because ads can't have both `[aria-label]` & `[aria-labelledby]` at the same time, afaik

cc @wizmak @manuel-martinez-dev

**Comment by arsykan** [comment]
image

**Comment by peace2000** [comment]
Interesting, don't know why I have both `[aria-label]` and `[aria-labelledby]`... Despite changing language and browser.

But anyway, if you think that's it's better to leave `[aria-label]` out, you can edit my pull request.

**Comment by wizmak** [comment]
Hey @peace2000 
The one change I see can be added so that the filter still works across different browsers is `[role="link"]` which I think won't make any difference in this case.
If there is nothing else you'd like to highlight/discuss, can we close this PR?

**Comment by peace2000** [comment]
@wizmak I can't edit this PR properly is it's conflicting, but anyway, you do as you feel it's good way to go, but I think that adding one attribute more could make it safer. Facebook changes their site sometimes (they did that very recently concerning their ads to make it harder to block them) so it's safer to have more specific filter so that it's more unlikely that it will cause incorrect blocking if FB does something.

**Comment by wizmak** [comment]
@peace2000 No worries, all should be good now.

**Pull request merged**
