### PR TITLE
Moving over all #$# entries from Nordic Filters' ABP version

### PR DESCRIPTION
**Pull request by DandelionSprout**
I have virtually no idea what most of these entries do, but @mile-ne (who also wanted to be tagged by me more often, from what I understood) firmly insisted over the course of some months that I had to submit this PR here. ~~My counterproposition is that this PR must be accepted before I'll remove the entries from Nordic Filters.~~

### CODE REVIEW

**Comment by wizmak** [comment]
@DandelionSprout 
In order for snippet filters (filters with the `#$#` marker) to work in ABP, they must be added to the anti-cv list, the corresponding snippets won't execute if such filters were coming from any other filter list, they still work if added locally though.

Before this PR is accepted, I need to know what these filters do, i.e. what problems do they fix.

**Comment by DandelionSprout** [comment]
Okay, so of the 72 entries, I can only easily attest to two of them: `gamer.no,tu.no#$#abort-current-inline-script dfpConfig loadAds` being meant to prevent ads from being loaded, and `vg.no#$#abort-current-inline-script Math.floor g00` being meant to prevent the site from entering g00 mode.

**Comment by llacb47** [comment]
`g00 mode` is not a thing - Instart Logic no longer exists.

**Comment by DandelionSprout** [comment]
As a result of me having realised that entry/list requirements in ABP were more strict than I had previously presumed they were, I also hereby withdraw my counterproposition and have also removed the `#$#` entries from *Dandelion Sprout's Nordic Filters*' ABP version and from *Swedish List for Adblock Plus* after all.

**Comment by wizmak** [comment]
@DandelionSprout 
I still need to know what all filters do before I can accept this PR, screenshots/descriptions would be sufficient. Also, The filter `vg.no#$#abort-current-inline-script Math.floor g00` is still included in the changes.
Thank you for your understanding.

**Comment by DandelionSprout** [comment]
Given the fact I don't know the purpose of 70 of them, I have become aware that I've got few other choices than to close this PR, with the possibility of proposing `gamer.no,tu.no#$#abort-current-inline-script dfpConfig loadAds` in a different PR at some point in the near future.

**Pull request closed without merging**
