### PR TITLE
A: MISC #742

### PR DESCRIPTION
**Pull request by felippesantos46**
Block popunders at [NSFW] https://4kporn.xxx/

Proposed filter: `4kporn.xxx#$#abort-property-on-read flashvars`

Screenshot:
Screenshot 2021-12-09 at 06 54 38

### CODE REVIEW

**Comment by mapx-** [comment]
Are you sure ? The videos will be broken

see `https://4kporn.xxx/videos/340585/ebony-barbie-bj/`

use an equivalent of uBO filter here:

`4kporn.xxx##+js(set, flashvars.popunder_url, '')`

**Comment by felippesantos46** [comment]
Hey @mapx- Thank you for the review. 

On my side the videos are not breaking at all. 
Getting the hit and everything seems to be ok. 😅
Screenshot 2021-12-09 at 09 13 28

**Comment by mapx-** [comment]
strange, flashvars has all the parameters - for running the videos too

**Comment by mapx-** [comment]
tested in ABP, it does not work consistently, so I guess it's the reason you still see the video

add this 1, working fine

`4kporn.xxx#$#override-property-read flashvars.popunder_url ''`

**Comment by wizmak** [comment]
@felippesantos46 There is a typo the added filter, it has `abort-property-on-read` instead of `abort-on-property-read`
if corrected, it does break videos as @mapx- mentioned above.

**Comment by mapx-** [comment]
@wizmak and this is a bug in ABP itself, it should report in the devtools log ONLY the correct snippets

**Comment by wizmak** [comment]
> @wizmak and this is a bug in ABP itself, it should report in the devtools log ONLY the correct snippets

@mapx- Yes, there are plans to make logging of snippet filters more reliable.

**Comment by felippesantos46** [comment]
@wizmak and @mapx- True that ! sorry about the typo, my bad !
I'm closing this one tho.

**Pull request closed without merging**
