### PR TITLE
M: linknerverdie.net anti adblock

### PR DESCRIPTION
**Pull request by hoang-rio**

### CODE REVIEW

**Comment by wizmak** [comment]
Hey @hoang-rio 
The anti-cv list is not meant to address anti adblock messages/walls/etc. I'd have to close this PR without merging it.
Thanks for your contribution!

**Comment by hoang-rio** [comment]
@wizmak Thanks. Now i know it. I will not create similar pull request

**Comment by mapx-** [comment]
fixed for uBO adblocker

**Comment by hoang-rio** [comment]
> fixed for uBO adblocker

ABPVN also do it before this pull request

**Pull request closed without merging**
