### PR TITLE
Fix ads on gfycat.com

### PR DESCRIPTION
**Pull request by ryanbr**
Not sure if its Instart Logic. but this will block it.

### CODE REVIEW

**Comment by ryanbr** [comment]
Okay, not definitely sure its instant logic

**Comment by ryanbr** [comment]
Alternatively, this may work
`gfycat.com#$#abort-current-inline-script Math`

**Comment by wizmak** [comment]
@ryanbr 
Went with `gfycat.com#$#abort-current-inline-script Math`, the other filter breaks the website. Thanks!

**Comment by dimisa-RUAdList** [comment]
@wizmak 
False positive here: 
`https://3dnews.ru/1043866/razrabotchiki-baldurs-gate-3-podelilis-podrobnostyami-pyatogo-krupnogo-patcha-on-viydet-13-iyulya`

**Pull request closed without merging**
