### PR TITLE
Improve ign.com, ignboards.com filter

### PR DESCRIPTION
**Pull request by ryanbr**
We could block these ads easier with a snippet.

No need to block elements. If we abort the JSON.stringify used on the site it'll fix this ad elements.

### CODE REVIEW

**Comment by wizmak** [comment]
This also blocks the website's "Support IGN/Whitelist Us" message to ad blockers users, would be nice if there is a way around that.

**Comment by ryanbr** [comment]
Actually it didn't stop the support IGN message from showing.

**Comment by ryanbr** [comment]
ign

**Comment by wizmak** [comment]
> Actually it didn't stop the support IGN message from showing.

Interesting, I indeed see that it does not stop it on Firefox, but it does on Chrome.

**Comment by ryanbr** [comment]
Okay, `ign.com` has the warning, while `ignboards.com` doesn't.

So these should help, re-tested in Chrome also.

**Comment by wizmak** [comment]
Looks good, thanks!

**Pull request merged**
