### PR TITLE
added polish snippets

### PR DESCRIPTION
**Pull request by manuel-martinez-dev**
located some CV issues on some polish websites, and the following snippets work on them.

### CODE REVIEW

**Comment by wizmak** [comment]
@manuel-martinez-dev Thanks for submitting this PR.

Aborting  `window.prebidConfig` seems to break images on `finanse.wp.pl` (need to scroll down, nearly after the second half of the page)

**Comment by manuel-martinez-dev** [comment]
@wizmak thanks for checking... 
I did not notice any images being broken while testing.... I think it might be due to cookies, as there is a slight delay in image load when the website is visited for the first time.

**Comment by wizmak** [comment]
> @wizmak thanks for checking...
> I did not notice any images being broken while testing.... I think it might be due to cookies, as there is a slight delay in image load when the website is visited for the first time.

@manuel-martinez-dev you're welcome!

But now I'm not sure which filter is breaking images, `finanse.wp.pl#$#abort-on-property-read prebidConfig` works fine for me ATM, while `abort-on-property-write habahaba` alone is breaking images. Let me ping the polish list author to get what he experiences.

@adblock-filters can you take a look?

**Comment by manuel-martinez-dev** [comment]
@wizmak I tried with both and could not see any big issues, that's why suggesting both seemed the right call, but if `finanse.wp.pl#$#abort-on-property-read prebidConfig` does the trick, then I guess there is no need to have them both and only one can be added.

**Comment by adblock-filters** [comment]
@wizmak On Chrome `finanse.wp.pl#$#abort-on-property-read prebidConfig` sometimes breaks video player (inside articles).
Maybe something more specific like `finanse.wp.pl#$#abort-on-property-read prebidConfig.hbA` would do the job.
This one blocks ad slots and leaves video player slot untouched.

**Comment by wizmak** [comment]
> @wizmak On Chrome `finanse.wp.pl#$#abort-on-property-read prebidConfig` sometimes breaks video player (inside articles).
> Maybe something more specific like `finanse.wp.pl#$#abort-on-property-read prebidConfig.hbA` would do the job.
> This one blocks ad slots and leaves video player slot untouched.

True, I went with your suggestion.

@manuel-martinez-dev @adblock-filters Thank you both!

**Pull request merged**
