### PR TITLE
Fix ads on kansas.com

### PR DESCRIPTION
**Pull request by ryanbr**
Same ads from on 9to5google, 9to5mac etc.

### CODE REVIEW

**Comment by wizmak** [comment]
> 9to5google.com,9to5mac.com,9to5toys.com,dronedj.com,electrek.co,kansas.com,marketrealist.com#$#abort-on-property-read $aproxy

@ryanbr the filter above doesn't seem to work anymore, can you double-check?

**Comment by ryanbr** [comment]
How about `kansas.com#$#abort-on-property-read localStorage`

**Comment by ryanbr** [comment]
Okay, need to figure out a better solution

**Comment by mapx-** [comment]
There are 2 categories:
`9to5google.com,9to5mac.com,9to5toys.com,dronedj.com,electrek.co,marketrealist.com`
`kansas.com,thenewstribune.com`

different filters (see uBo - last adjustments)

**Pull request merged**
